//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masrofy4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Masrofy4Entities : DbContext
    {
        public Masrofy4Entities()
            : base("name=Masrofy4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int ChangeMobilenum(string mobilenum, string nid)
        {
            var mobilenumParameter = mobilenum != null ?
                new ObjectParameter("mobilenum", mobilenum) :
                new ObjectParameter("mobilenum", typeof(string));
    
            var nidParameter = nid != null ?
                new ObjectParameter("nid", nid) :
                new ObjectParameter("nid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeMobilenum", mobilenumParameter, nidParameter);
        }
    
        public virtual int ChangeName(string fullname, string nid)
        {
            var fullnameParameter = fullname != null ?
                new ObjectParameter("fullname", fullname) :
                new ObjectParameter("fullname", typeof(string));
    
            var nidParameter = nid != null ?
                new ObjectParameter("nid", nid) :
                new ObjectParameter("nid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeName", fullnameParameter, nidParameter);
        }
    
        public virtual int ChangePasswordByOTP(string nationalID, string new_pw)
        {
            var nationalIDParameter = nationalID != null ?
                new ObjectParameter("nationalID", nationalID) :
                new ObjectParameter("nationalID", typeof(string));
    
            var new_pwParameter = new_pw != null ?
                new ObjectParameter("new_pw", new_pw) :
                new ObjectParameter("new_pw", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangePasswordByOTP", nationalIDParameter, new_pwParameter);
        }
    
        public virtual int ChangePwd(string nid, string pwd)
        {
            var nidParameter = nid != null ?
                new ObjectParameter("nid", nid) :
                new ObjectParameter("nid", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangePwd", nidParameter, pwdParameter);
        }
    
        public virtual ObjectResult<string> CheckUserExistence(string nationalID, string mobileNum, string name, string username)
        {
            var nationalIDParameter = nationalID != null ?
                new ObjectParameter("nationalID", nationalID) :
                new ObjectParameter("nationalID", typeof(string));
    
            var mobileNumParameter = mobileNum != null ?
                new ObjectParameter("mobileNum", mobileNum) :
                new ObjectParameter("mobileNum", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CheckUserExistence", nationalIDParameter, mobileNumParameter, nameParameter, usernameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> FindUsernames(string uname)
        {
            var unameParameter = uname != null ?
                new ObjectParameter("uname", uname) :
                new ObjectParameter("uname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("FindUsernames", unameParameter);
        }
    
        public virtual ObjectResult<string> GetMobilenum(string nid)
        {
            var nidParameter = nid != null ?
                new ObjectParameter("nid", nid) :
                new ObjectParameter("nid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetMobilenum", nidParameter);
        }
    
        public virtual ObjectResult<string> GetName(string nid)
        {
            var nidParameter = nid != null ?
                new ObjectParameter("nid", nid) :
                new ObjectParameter("nid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetName", nidParameter);
        }
    
        public virtual ObjectResult<GetOTP_Result> GetOTP(string nationalID)
        {
            var nationalIDParameter = nationalID != null ?
                new ObjectParameter("nationalID", nationalID) :
                new ObjectParameter("nationalID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOTP_Result>("GetOTP", nationalIDParameter);
        }
    
        public virtual ObjectResult<string> GetPwd(string nid)
        {
            var nidParameter = nid != null ?
                new ObjectParameter("nid", nid) :
                new ObjectParameter("nid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetPwd", nidParameter);
        }
    
        public virtual ObjectResult<string> GetUserFullName(string nid)
        {
            var nidParameter = nid != null ?
                new ObjectParameter("nid", nid) :
                new ObjectParameter("nid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetUserFullName", nidParameter);
        }
    
        public virtual int Signup(string nid, string mobileno, string fullname, string username, string pwd)
        {
            var nidParameter = nid != null ?
                new ObjectParameter("nid", nid) :
                new ObjectParameter("nid", typeof(string));
    
            var mobilenoParameter = mobileno != null ?
                new ObjectParameter("mobileno", mobileno) :
                new ObjectParameter("mobileno", typeof(string));
    
            var fullnameParameter = fullname != null ?
                new ObjectParameter("fullname", fullname) :
                new ObjectParameter("fullname", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Signup", nidParameter, mobilenoParameter, fullnameParameter, usernameParameter, pwdParameter);
        }
    
        public virtual int StoreOTP(string nationalID, string oKey, Nullable<System.DateTime> odate)
        {
            var nationalIDParameter = nationalID != null ?
                new ObjectParameter("nationalID", nationalID) :
                new ObjectParameter("nationalID", typeof(string));
    
            var oKeyParameter = oKey != null ?
                new ObjectParameter("oKey", oKey) :
                new ObjectParameter("oKey", typeof(string));
    
            var odateParameter = odate.HasValue ?
                new ObjectParameter("odate", odate) :
                new ObjectParameter("odate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("StoreOTP", nationalIDParameter, oKeyParameter, odateParameter);
        }
    
        public virtual ObjectResult<string> UserLogin4(string usr, string pwd)
        {
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("UserLogin4", usrParameter, pwdParameter);
        }
    }
}
